export const playerActionTypes = {
    FETCH_MOVIE: 'FETCH_MOVIE',
    FETCH_MOVIE_FAILURE: 'FETCH_MOVIE_FAILURE',
    FETCH_MOVIE_SUCCESS: 'FETCH_MOVIE_SUCCESS',
    FETCH_SERIES: 'FETCH_SERIES',
    FETCH_SERIES_FAILURE: 'FETCH_SERIES_FAILURE',
    FETCH_SERIES_SUCCESS: 'FETCH_SERIES_SUCCESS'
}