export const seriesActionTypes = {
    FETCH_POPULAR_SERIES_REQUEST: 'FETCH_POPULAR_SERIES_REQUEST',
    FETCH_POPULAR_SERIES_SUCCESS: 'FETCH_POPULAR_SERIES_SUCCESS',
    FETCH_POPULAR_SERIES_FAILURE: 'FETCH_POPULAR_SERIES_FAILURE',
    LOAD_MORE_POPULAR_SERIES_SUCCESS: 'LOAD_MORE_POPULAR_SERIES_SUCCESS',

    FETCH_ACTION_SERIES_REQUEST: 'FETCH_ACTION_SERIES_REQUEST',
    FETCH_ACTION_SERIES_SUCCESS: 'FETCH_ACTION_SERIES_SUCCESS',
    FETCH_ACTION_SERIES_FAILURE: 'FETCH_ACTION_SERIES_FAILURE',
    LOAD_MORE_ACTION_SERIES_SUCCESS: 'LOAD_MORE_ACTION_SERIES_SUCCESS',

    FETCH_COMEDY_SERIES_REQUEST: 'FETCH_COMEDY_SERIES_REQUEST',
    FETCH_COMEDY_SERIES_SUCCESS: 'FETCH_COMEDY_SERIES_SUCCESS',
    FETCH_COMEDY_SERIES_FAILURE: 'FETCH_COMEDY_SERIES_FAILURE',
    LOAD_MORE_COMEDY_SERIES_SUCCESS: 'LOAD_MORE_COMEDY_SERIES_SUCCESS',

    FETCH_DRAMA_SERIES_REQUEST: 'FETCH_DRAMA_SERIES_REQUEST',
    FETCH_DRAMA_SERIES_SUCCESS: 'FETCH_DRAMA_SERIES_SUCCESS',
    FETCH_DRAMA_SERIES_FAILURE: 'FETCH_DRAMA_SERIES_FAILURE',
    LOAD_MORE_DRAMA_SERIES_SUCCESS: 'LOAD_MORE_DRAMA_SERIES_SUCCESS',

    FETCH_HORROR_SERIES_REQUEST: 'FETCH_HORROR_SERIES_REQUEST',
    FETCH_HORROR_SERIES_SUCCESS: 'FETCH_HORROR_SERIES_SUCCESS',
    FETCH_HORROR_SERIES_FAILURE: 'FETCH_HORROR_SERIES_FAILURE',
    LOAD_MORE_HORROR_SERIES_SUCCESS: 'LOAD_MORE_HORROR_SERIES_SUCCESS',

    FETCH_THRILLER_SERIES_REQUEST: 'FETCH_THRILLER_SERIES_REQUEST',
    FETCH_THRILLER_SERIES_SUCCESS: 'FETCH_THRILLER_SERIES_SUCCESS',
    FETCH_THRILLER_SERIES_FAILURE: 'FETCH_THRILLER_SERIES_FAILURE',
    LOAD_MORE_THRILLER_SERIES_SUCCESS: 'LOAD_MORE_THRILLER_SERIES_SUCCESS',


    FETCH_LATEST_SERIES_REQUEST: 'FETCH_LATEST_SERIES_REQUEST',
    FETCH_LATEST_SERIES_SUCCESS: 'FETCH_LATEST_SERIES_SUCCESS',
    FETCH_LATEST_SERIES_FAILURE: 'FETCH_LATEST_SERIES_FAILURE',
    LOAD_MORE_LATEST_SERIES_SUCCESS: 'LOAD_MORE_LATEST_SERIES_SUCCESS',

    FETCH_RECOMMENDED_SERIES_REQUEST: 'FETCH_RECOMMENDED_SERIES_REQUEST',
    FETCH_RECOMMENDED_SERIES_SUCCESS: 'FETCH_RECOMMENDED_SERIES_SUCCESS',
    FETCH_RECOMMENDED_SERIES_FAILURE: 'FETCH_RECOMMENDED_SERIES_FAILURE',
    LOAD_MORE_RECOMMENDED_SERIES_SUCCESS: 'LOAD_MORE_RECOMMENDED_SERIES_SUCCESS',
}