export const moviesActionTypes = {
    FETCH_POPULAR_MOVIES_REQUEST: 'FETCH_POPULAR_MOVIES_REQUEST',
    FETCH_POPULAR_MOVIES_SUCCESS: 'FETCH_POPULAR_MOVIES_SUCCESS',
    FETCH_POPULAR_MOVIES_FAILURE: 'FETCH_POPULAR_MOVIES_FAILURE',
    LOAD_MORE_POPULAR_MOVIES_SUCCESS: 'LOAD_MORE_POPULAR_MOVIES_SUCCESS',

    FETCH_ACTION_MOVIES_REQUEST: 'FETCH_ACTION_MOVIES_REQUEST',
    FETCH_ACTION_MOVIES_SUCCESS: 'FETCH_ACTION_MOVIES_SUCCESS',
    FETCH_ACTION_MOVIES_FAILURE: 'FETCH_ACTION_MOVIES_FAILURE',
    LOAD_MORE_ACTION_MOVIES_SUCCESS: 'LOAD_MORE_ACTION_MOVIES_SUCCESS',

    FETCH_COMEDY_MOVIES_REQUEST: 'FETCH_COMEDY_MOVIES_REQUEST',
    FETCH_COMEDY_MOVIES_SUCCESS: 'FETCH_COMEDY_MOVIES_SUCCESS',
    FETCH_COMEDY_MOVIES_FAILURE: 'FETCH_COMEDY_MOVIES_FAILURE',
    LOAD_MORE_COMEDY_MOVIES_SUCCESS: 'LOAD_MORE_COMEDY_MOVIES_SUCCESS',

    FETCH_DRAMA_MOVIES_REQUEST: 'FETCH_DRAMA_MOVIES_REQUEST',
    FETCH_DRAMA_MOVIES_SUCCESS: 'FETCH_DRAMA_MOVIES_SUCCESS',
    FETCH_DRAMA_MOVIES_FAILURE: 'FETCH_DRAMA_MOVIES_FAILURE',
    LOAD_MORE_DRAMA_MOVIES_SUCCESS: 'LOAD_MORE_DRAMA_MOVIES_SUCCESS',

    FETCH_HORROR_MOVIES_REQUEST: 'FETCH_HORROR_MOVIES_REQUEST',
    FETCH_HORROR_MOVIES_SUCCESS: 'FETCH_HORROR_MOVIES_SUCCESS',
    FETCH_HORROR_MOVIES_FAILURE: 'FETCH_HORROR_MOVIES_FAILURE',
    LOAD_MORE_HORROR_MOVIES_SUCCESS: 'LOAD_MORE_HORROR_MOVIES_SUCCESS',

    FETCH_THRILLER_MOVIES_REQUEST: 'FETCH_THRILLER_MOVIES_REQUEST',
    FETCH_THRILLER_MOVIES_SUCCESS: 'FETCH_THRILLER_MOVIES_SUCCESS',
    FETCH_THRILLER_MOVIES_FAILURE: 'FETCH_THRILLER_MOVIES_FAILURE',
    LOAD_MORE_THRILLER_MOVIES_SUCCESS: 'LOAD_MORE_THRILLER_MOVIES_SUCCESS',


    FETCH_LATEST_MOVIES_REQUEST: 'FETCH_LATEST_MOVIES_REQUEST',
    FETCH_LATEST_MOVIES_SUCCESS: 'FETCH_LATEST_MOVIES_SUCCESS',
    FETCH_LATEST_MOVIES_FAILURE: 'FETCH_LATEST_MOVIES_FAILURE',
    LOAD_MORE_LATEST_MOVIES_SUCCESS: 'LOAD_MORE_LATEST_MOVIES_SUCCESS',

    FETCH_RECOMMENDED_MOVIES_REQUEST: 'FETCH_RECOMMENDED_MOVIES_REQUEST',
    FETCH_RECOMMENDED_MOVIES_SUCCESS: 'FETCH_RECOMMENDED_MOVIES_SUCCESS',
    FETCH_RECOMMENDED_MOVIES_FAILURE: 'FETCH_RECOMMENDED_MOVIES_FAILURE',
    LOAD_MORE_RECOMMENDED_MOVIES_SUCCESS: 'LOAD_MORE_RECOMMENDED_MOVIES_SUCCESS',
}