export const moviesActionTypes = {
    FETCH_POPULAR_MOVIES_REQUEST: 'FETCH_POPULAR_MOVIES_REQUEST',
    FETCH_POPULAR_MOVIES_SUCCESS: 'FETCH_POPULAR_MOVIES_SUCCESS',
    FETCH_POPULAR_MOVIES_FAILURE: 'FETCH_POPULAR_MOVIES_FAILURE',
    LOAD_MORE_POPULAR_MOVIES_SUCCESS: 'LOAD_MORE_POPULAR_MOVIES_SUCCESS',
}